### ISSUE TITLE
Spanish translation for "Fix or Kill Automatically Installed JavaScript?"

### ISSUE THREAD

**Issue by jorgesumle** [onpon4/onpon4.github.io#2]
I'm going to translate the article "Fix or Kill Automatically Installed JavaScript?" into Spanish. It would be great if I could add the translated article to your website. If you're willing to accept it, tell me how I should add it.

If you prefer not to add it, I can upload it to [Freak Spot](https://freakspot.net/) respecting your license. In that case, please tell me whom I should attribute (The Diligent Circle,  Julie Marchant?).

**Comment by onpon4** [comment]
I'm not interested in maintaining translations, so Freak Spot is probably the better choice. As for attribution, "Julie Marchant" is fine, and "The Diligent Circle" would be fine too. I don't particularly care which you use.

**Comment by jorgesumle** [comment]
The translation is [Arreglar o matar el JavaScript instalado automáticamente](https://freakspot.net/arreglar-o-matar-el-javascript-instalado-automáticamente).
